---
- hosts: hostB
  remote_user:  centos
  sudo: yes
  gather_facts: no
  environment:
        http_proxy: http://10.222.192.4:8080
        https_proxy: http://10.222.192.4:8080
  tasks:     
      - name: upgrade all packages
        yum: name=* state=latest
        
        
      - copy: src=install_docker/overlay.conf
              dest=/etc/modules-load.d/overlay.conf
        
        
      - copy: src=install_docker/docker.repo
              dest=/etc/yum.repos.d/docker.repo 
 #     - name: Create file
 #       file: path=/tmp/yallo2 state=touch
      - name: Create directory     
        file: path=/etc/systemd/system/docker.service.d  state=directory       
          
       - copy: src=install_docker/override.conf
         dest=/etc/systemd/system/docker.service.d/override.conf
 
     # - name: create a path
      #  command: mkdir -p /etc/systemd/system/docker.service.d
      #  register: mymotd             
      
   
            
      - name: Install docker-engine-1.13.1
        yum: name=docker-engine-1.13.1 
            
- hosts: my_hosts
  sudo: yes
  tasks:
      - name: Create user
        user: name=mario shell=/bin/zsh

      - name: Install zlib
        yum: name=zlib state=latest
